name = "Airlands"
author = "Oliver"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc96b23fe8d48802466026b8a956165ca9809383a69edc3dbae1219af8cbb849"

[versions]
forge = "39.1.0"
minecraft = "1.18.1"
