name = "AppleSkin"
filename = "appleskin-forge-mc1.18-2.3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/forge-mc1.18-2.3.0/appleskin-forge-mc1.18-2.3.0.jar"
hash-format = "sha1"
hash = "1c5ffe0ae1bebb1b22d1abbe2b882a29785093aa"

[update]
[update.modrinth]
mod-id = "EsAfCjCV"
version = "FuDL4moO"
