name = "Architectury API (Forge)"
filename = "architectury-3.7.31.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/605/architectury-3.7.31.jar"
hash-format = "sha1"
hash = "8484d116119b1c49dce7a13cb38b723514fc615b"

[update]
[update.curseforge]
file-id = 3671605
project-id = 419699
