name = "ExtraStorage"
filename = "ExtraStorage-1.18.1-2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3584/356/ExtraStorage-1.18.1-2.0.1.jar"
hash-format = "sha1"
hash = "a40aa85a4812b935da3a101db6ca49ea83752187"

[update]
[update.curseforge]
file-id = 3584356
project-id = 410168
