name = "Mantle"
filename = "Mantle-1.18.1-1.8.31.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3634/761/Mantle-1.18.1-1.8.31.jar"
hash-format = "sha1"
hash = "718ac166a5031c1bdacedf1127170fc80877af6c"

[update]
[update.curseforge]
file-id = 3634761
project-id = 74924
