name = "Origins (Forge)"
filename = "Origins-1.18.1-1.3.1.0-unified.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3693/172/Origins-1.18.1-1.3.1.0-unified.jar"
hash-format = "sha1"
hash = "3753e771edcf4b43bc1f9c25c38817f3c6cf9ee8"

[update]
[update.curseforge]
file-id = 3693172
project-id = 474438
