name = "Refined Storage"
filename = "refinedstorage-1.10.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/324/refinedstorage-1.10.0.jar"
hash-format = "sha1"
hash = "8df7e8a3a2badc1636f71b25c6863835e6182ab7"

[update]
[update.curseforge]
file-id = 3623324
project-id = 243076
