name = "REI Compatibility Workaround"
filename = "RoughlyEnoughItems-jei-internals-workaround-7.3.443.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/494/RoughlyEnoughItems-jei-internals-workaround-7.3.443.jar"
hash-format = "sha1"
hash = "501532cf6f3722d3db12887b8b449527a672332f"

[update]
[update.curseforge]
file-id = 3670494
project-id = 521393
